const words=[
['Hello','Hola','Hello, how are you?','Hola, ¿cómo estás?'],['Good morning','Buenos días','Good morning, everyone.','Buenos días a todos.'],['Friend','Amigo','My friend is here.','Mi amigo está aquí.'],['Family','Familia','I love my family.','Amo a mi familia.'],['House','Casa','This is my house.','Esta es mi casa.'],['School','Escuela','I go to school.','Voy a la escuela.'],['Book','Libro','This book is interesting.','Este libro es interesante.'],['Water','Agua','I drink water.','Bebo agua.'],['Food','Comida','The food is good.','La comida está buena.'],['Work','Trabajo','I have work today.','Tengo trabajo hoy.'],['Happy','Feliz','I am happy today.','Estoy feliz hoy.'],['Beautiful','Hermoso/a','It is a beautiful day.','Es un día hermoso.'],['Learn','Aprender','I learn English.','Aprendo inglés.'],['Speak','Hablar','I speak English.','Hablo inglés.'],['Listen','Escuchar','Listen to me, please.','Escúchame, por favor.'],['Understand','Entender','I understand the question.','Entiendo la pregunta.'],['Today','Hoy','Today is Monday.','Hoy es lunes.'],['Tomorrow','Mañana','See you tomorrow.','Nos vemos mañana.'],['Always','Siempre','I always study.','Siempre estudio.'],['Sometimes','A veces','I sometimes read.','A veces leo.']];
const grammar=[['Verb to be','Usamos am, is y are para decir quiénes somos, describir estados o identificar algo.','I am a student. / She is happy. / They are friends.'],['Present Simple','Se usa para rutinas, hábitos y hechos. Con he/she/it normalmente agregamos -s al verbo.','I study every day. / He works here.'],['Have / Has','Have se usa con I/you/we/they; has con he/she/it.','I have a book. / She has a car.'],['There is / There are','There is para una cosa y there are para varias.','There is a school. / There are two books.'],['Can / Can’t','Can expresa habilidad o posibilidad; can’t expresa que no podemos.','I can speak English. / I can’t swim.']];
const phrases=[['How are you?','¿Cómo estás?'],['Nice to meet you.','Mucho gusto.'],['What is your name?','¿Cuál es tu nombre?'],['Where are you from?','¿De dónde eres?'],['I don’t understand.','No entiendo.'],['Can you repeat, please?','¿Puedes repetir, por favor?'],['What does this mean?','¿Qué significa esto?'],['See you later.','Nos vemos luego.'],['Have a nice day!','¡Que tengas un buen día!'],['Thank you very much.','Muchas gracias.'],['Excuse me.','Disculpe / Perdón.'],['You’re welcome.','De nada.']];
let state=JSON.parse(localStorage.getItem('englishComState')||'null')||{learned:[],points:0,best:0,activity:0,days:[],last:null,streak:0};
const save=()=>localStorage.setItem('englishComState',JSON.stringify(state));
function activity(n=1){state.activity+=n;state.points+=n;const d=new Date().toISOString().slice(0,10);if(state.last!==d){state.days.push(d);if(state.last){const diff=(new Date(d)-new Date(state.last))/86400000;state.streak=diff===1?state.streak+1:1}else state.streak=1;state.last=d}save();renderStats()}
function renderStats(){const p=Math.min(100,state.activity*10);document.querySelector('#learned').textContent=state.learned.length;document.querySelector('#quizScore').textContent=state.best;document.querySelector('#studyDays').textContent=state.days.length;document.querySelector('#points').textContent=state.points;document.querySelector('#streak').textContent=state.streak;document.querySelector('#goalPct').textContent=p+'%';document.querySelector('#sideGoal').textContent=Math.min(state.activity,10)+' / 10';document.querySelector('#sideBar').style.width=p+'%';document.querySelector('#progressPct').textContent=p+'%';document.querySelector('#progressLine').style.width=p+'%';document.querySelector('#achStreak').textContent=state.streak;document.querySelector('#achWords').textContent=state.learned.length;document.querySelector('#achPoints').textContent=state.points;document.querySelector('#achBest').textContent=state.best}
function renderVocab(filter=''){const g=document.querySelector('#vocabGrid');g.innerHTML=words.filter(w=>w[0].toLowerCase().includes(filter.toLowerCase())||w[1].toLowerCase().includes(filter.toLowerCase())).map((w,i)=>`<article class="word-card"><button onclick="speak('${w[0]}')">🔊</button><b>${w[0]}</b><span class="es">${w[1]}</span><small>${w[2]}</small></article>`).join('')}
function renderGrammar(){document.querySelector('#grammarList').innerHTML=grammar.map(g=>`<article class="grammar-card"><h3>${g[0]}</h3><p>${g[1]}</p><div class="example">${g[2]}</div></article>`).join('')}
function renderPhrases(){document.querySelector('#phraseGrid').innerHTML=phrases.map(p=>`<article class="phrase-card"><b>${p[0]}</b><span>${p[1]}</span><button class="secondary" onclick="speak('${p[0]}')">🔊 Escuchar</button></article>`).join('')}
let fc=0;function renderCard(){const w=words[fc];document.querySelector('#fcWord').textContent=w[0];document.querySelector('#fcEs').textContent=w[1];document.querySelector('#fcExample').textContent=w[2];document.querySelector('#fcExampleEs').textContent=w[3];document.querySelector('#flashcard').classList.remove('flipped')}
function speak(text){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.85;speechSynthesis.speak(u)}}
const questions=[...words.slice(0,12)].map((w,i)=>({q:`¿Qué significa “${w[0]}”?`,opts:[w[1],words[(i+3)%words.length][1],words[(i+7)%words.length][1],words[(i+11)%words.length][1]],a:w[1]}));let qi=0,score=0,answered=false;
function startQuiz(){qi=0;score=0;answered=false;document.querySelector('#quizResult').classList.add('hidden');showQuestion()}
function showQuestion(){const x=questions[qi];document.querySelector('#qProgress').textContent=`Pregunta ${qi+1} de ${questions.length-2}`;document.querySelector('#qScore').textContent=score+' pts';document.querySelector('#qBar').style.width=(qi/(questions.length-2)*100)+'%';document.querySelector('#question').textContent=x.q;const a=document.querySelector('#answers');a.innerHTML=x.opts.map((o,i)=>`<button class="answer" data-answer="${o.replaceAll('"','&quot;')}">${o}</button>`).join('');document.querySelector('#nextQ').disabled=true;answered=false;a.querySelectorAll('.answer').forEach(b=>b.onclick=()=>choose(b,x.a));}
function choose(btn,correct){if(answered)return;answered=true;const all=[...document.querySelectorAll('.answer')];all.forEach(b=>{if(b.textContent===correct)b.classList.add('correct')});if(btn.textContent===correct){score+=10;btn.classList.add('correct')}else btn.classList.add('wrong');document.querySelector('#qScore').textContent=score+' pts';document.querySelector('#nextQ').disabled=false;activity()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.section));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));function go(id){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.querySelector('#'+id).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.section===id));if(id==='quiz')startQuiz();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#search').oninput=e=>renderVocab(e.target.value);document.querySelector('#flashcard').onclick=()=>document.querySelector('#flashcard').classList.toggle('flipped');document.querySelector('#prevCard').onclick=()=>{fc=(fc-1+words.length)%words.length;renderCard()};document.querySelector('#nextCard').onclick=()=>{fc=(fc+1)%words.length;renderCard()};document.querySelector('#knownBtn').onclick=()=>{if(!state.learned.includes(words[fc][0]))state.learned.push(words[fc][0]);activity();fc=(fc+1)%words.length;renderCard()};document.querySelector('#speakBtn').onclick=()=>speak(words[fc][0]);document.querySelector('#listenBtn').onclick=()=>speak(document.querySelector('#listenText').textContent);document.querySelector('#nextQ').onclick=()=>{if(qi<questions.length-3){qi++;showQuestion()}else{if(score>state.best)state.best=score;save();document.querySelector('#quizResult').classList.remove('hidden');document.querySelector('#quizResult').innerHTML=`<h3>🏆 Quiz terminado</h3><p>Conseguiste <b>${score} puntos</b>.</p><button class="primary" onclick="startQuiz()">Intentar de nuevo</button>`;document.querySelector('#nextQ').disabled=true;renderStats()}};document.querySelector('#resetBtn').onclick=()=>{if(confirm('¿Reiniciar todo tu progreso?')){localStorage.removeItem('englishComState');location.reload()}};document.querySelector('#langBtn').onclick=()=>alert('La interfaz está en español para ayudarte a aprender inglés. El contenido de práctica está en inglés y español.');renderVocab();renderGrammar();renderPhrases();renderCard();renderStats();
